# This file is never read -- it's just a copy of the pipeline's
# configuration in the Buildkite UI.

# This config is intended for running the rails/buildkite-config CI.

steps:
  - block: "Review Build Script"
    prompt: |
      Our CI scripts run outside the docker containers, which are a necessary security layer.

      Approving a build here is equivalent to copy & pasting it into a production ssh window.

      Prefer a second opinion for any nontrivial change, especially outside `pipeline-generate`.

      - @matthewd
  - command: |
      git config --global --add safe.directory /workdir
      bundle install
      bundle exec rake test
    key: self-test
    plugins:
      - docker#v5.8.0:
          image: "ruby:latest"
          propagate-environment: true
  - command: |
      git config --global --add safe.directory /workdir
      bundle install
      bundle exec rake diff
    key: diff
    depends_on: self-test
    plugins:
      - docker#v5.8.0:
          image: "ruby:latest"
          mount-buildkite-agent: true
          propagate-environment: true
          environment:
            - "GITHUB_TOKEN"
  - trigger: "rails-ci"
    label: ":pipeline: Build Rails main with new config"
    depends_on: diff
    build:
      message: "[${BUILDKITE_BRANCH}] ${BUILDKITE_MESSAGE}"
      branch: "main"
      env:
        CONFIG_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
        CONFIG_BRANCH: "${BUILDKITE_BRANCH}"
        BUILDKITE_CONFIG_TRIGGER: true # This variable can be used downstream to avoid things like "if branch==main do Y"
  - trigger: "rails-ci"
    label: ":pipeline: Build Rails 6-1-stable with new config"
    depends_on: diff
    build:
      message: "[${BUILDKITE_BRANCH} / 6-1-stable] ${BUILDKITE_MESSAGE}"
      branch: "6-1-stable"
      env:
        CONFIG_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
        CONFIG_BRANCH: "${BUILDKITE_BRANCH}"
        BUILDKITE_CONFIG_TRIGGER: true # This variable can be used downstream to avoid things like "if branch==main do Y"
